### ISSUE TITLE
Incorrect culling of objects on the plane Z=0 with 0 rotation.

### ISSUE THREAD

**Issue by dmkolobov** [Sunset-Studios/Sundown#1]
This is a great project!

In the example project, if I set the camera up like this prior to spawning the object grid:

```typescript
const context = Renderer.get().graphics_context;
 SharedViewBuffer.get().set_view_data(context, this.context.current_view, {
     position: vec4.fromValues(0.0, 0.0, -10.0, 1),
     rotation: quat.fromEuler(quat.create(), 0, 0, 0)
 });
```

then objects spawned on the plane Z=0 are culled when the camera is perpendicular to that plane. Moving around with WASD/QE has no effect. The objects pop into view when the rotation is changes via code or through shift+drag. 

Objects in front of or behind the culled ones are unaffected, and if the loop is modified to spawn objects with a small offset, the issue disappears.

If `culling_enabled` is set to 0 then the issue does not occur.

Do you know what the issue might be here? Would love to help resolve this issue but unfortunately my 3D graphics skills are a bit lacking.

**Comment by gitbetter** [comment]
@dmkolobov Thanks for spotting that, almost missed this! Looks like it may have been a simple numerical issue in the culling shader, with regards to how the depth range for the projected AABB of each object was getting calculated. Rewrote the shader a bit and this should be fixed now in the latest commit [9d27954](https://github.com/Sunset-Studios/Sundown/commit/9d27954fe9432116ef0fedd1cbc606e7b8f845e9)
